Create zh_cn.lang
CrafterKina/Pipes pull request #33
Opened 2017-07-28 07:43 UTC by Snownee

Purpose
---
Added Chinese translations for Pepis

Reason
---

2017-07-28 09:38 UTC, CrafterKina requested changes
Thanks!
There seems to be some copy and paste mistakes.

2017-07-28 09:38 UTC, CrafterKina commented on src/main/resources/assets/jp.crafterkina.pipes/lang/zh_cn.lang
> +advancement.jp.crafterkina.pipes.general.buildExtractionProcessor.desc=用处理器板和木板制作一枚加速器
提取器

2017-07-28 09:38 UTC, CrafterKina commented on src/main/resources/assets/jp.crafterkina.pipes/lang/zh_cn.lang
> +advancement.jp.crafterkina.pipes.general.buildOnewayProcessor.desc=用处理器板和铁锭制作一枚加速器
单向

2017-07-30 03:47 UTC, Snownee commented
Corrected

2017-07-30 06:42 UTC, CrafterKina approved these changes

2017-07-30 06:44 UTC, merged